rvm:
  - 2.1.3

bundler_args: --without development --path=~/.bundle

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

before_script:
  - bundle exec rake db:create db:migrate db:test:load

script:
  - bundle exec rspec spec


env:
  global:
  - RAILS_ENV=test
